version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_JMX_PORT: 9010
      KAFKA_JMX_HOSTNAME: zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9010
      KAFKA_JMX_HOSTNAME: kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - "8081:8081"
    links:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  jmx_exporter:
    image: sscaling/jmx-prometheus-exporter:latest
    ports:
      - "5556:5556"
    links:
      - kafka
    volumes:
      - ./jmx_exporter_config.yml:/opt/jmx_exporter/config.yml

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    links:
      - kafka
      - jmx_exporter
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - prometheus
