version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_JMX_PORT: 9010
      KAFKA_JMX_HOSTNAME: zookeeper
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "SSL://kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9010
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./secrets:/etc/kafka/secrets

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    ports:
      - "8081:8081"
    links:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "SSL://kafka:9092"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "SSL"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.consumer.keystore.jks"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: "test1234"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: "test1234"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.consumer.truststore.jks"
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: "test1234"
    volumes:
      - ./secrets:/etc/kafka/secrets

  jmx_exporter:
    image: sscaling/jmx-prometheus-exporter:latest
    ports:
      - "5556:5556"
    links:
      - kafka
    volumes:
      - ./config/jmx_exporter_config.yml:/opt/jmx_exporter/config.yml

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    links:
      - kafka
      - jmx_exporter
    volumes:
      - ./config/prometheus_config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - prometheus

  mysql:
    image: debezium/example-mysql:0.8
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

  connect:
    image: debezium/connect:0.8
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
      - schema-registry
    environment:
      BOOTSTRAP_SERVERS: "SSL://kafka:9092"
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/kafka.producer.keystore.jks"
      CONNECT_SSL_KEYSTORE_PASSWORD: "test1234"
      CONNECT_SSL_KEY_PASSWORD: "test1234"
      CONNECT_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/kafka.producer.truststore.jks"
      CONNECT_SSL_TRUSTSTORE_PASSWORD: "test1234"
      CONNECT_SECURITY_PROTOCOL: "SSL"
      HEAP_OPTS: -Xmx2G -Xms2G
    volumes:
      - ./secrets:/etc/kafka/secrets
