global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:

  - job_name: 'jmx'
    static_configs:
    - targets: ['jmx_exporter:5556']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']
